schemaVersion: 2.2.0
metadata:
  name: hello-jboss
  version: 1.0.0
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      mountSources: true
      env:
        - name: KUBEDOCK_ENABLED
          value: "true"
        - name: USE_JAVA17
          value: "true"
        - name: CONTAINER_HOST
          value: "tcp://127.0.0.1:2475"
      volumeMounts:
        - name: deployments
          path: /deployments
        - name: m2
          path: /tmp/m2
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475
        - exposure: public
          name: http-booster
          protocol: http
          targetPort: 8080
          attributes:
            discoverable: true
            urlRewriteSupported: true
        - exposure: internal
          name: debug
          protocol: http
          targetPort: 5005
  - name: deployments
    volume:
      size: 1Gi
  - name: m2
    volume:
      size: 1Gi
